feat(docker): add Docker Support and publish images to dockerhub
jef/nvidia-snatcher pull request #411
Opened 2020-10-02 00:43 UTC by V1ct0rV

### Description

This is another proposal based on #374 and #174 but using Github Actions to build and publish the images, I added the Dockerfile, a sample docker-compose.yml and, as part of CD, build the image and push to [DockerHub](https://hub.docker.com/r/v1ct0rv/nvidia-snatcher), so we will have the image with the latest code on main branch.

I also add documentation to use it.

2020-10-06 16:04 UTC, jef approved these changes
Before we start maintaining a Docker image, I'd prefer these changes go in for maintenance purposes.

Thanks!

2020-10-06 16:04 UTC, jef commented on docker/Dockerfile
> +CMD node index.js
No need to copy over `package.json` or `tsconfig.json`.

```suggestion
COPY --from=builder /build/node_modules/ node_modules/
COPY --from=builder /build/build/ build/

CMD [ "node", "./build/index.js" ]
```

2020-10-06 16:04 UTC, jef commented on README.md
> +
```suggestion
#### Docker image (To run inside containers)

Available via GitHub Container Registry. 

| Tag | Note |
|:---:|---|
| latest | Latest stable build |
| nightly | Latest HEAD build, could be unstable |

Use `docker run -it --rm --env-file ./.env ghcr.io/jef/nvidia-snatcher:nightly` to run.

```

2020-10-06 16:04 UTC, jef commented on README.md
> +#### Native installation (recommended)
```suggestion
#### Native installation
```

2020-10-06 16:05 UTC, jef requested changes
Feel free to ask any questions or concerns.

2020-10-06 16:13 UTC, kaysond commented
I would suggest changing the docker compose example to use a seccomp file like the one in #174 so you dont have to disable the chromium sandbox

2020-10-06 16:52 UTC, V1ct0rV commented
> Before we start maintaining a Docker image, I'd prefer these changes go in for maintenance purposes.
> 
> Thanks!

I apply your suggestions, thanks!

> I would suggest changing the docker compose example to use a seccomp file like the one in #174 so you dont have to disable the chromium sandbox

I just remove `docker-compose.yml` in order to use directly in cli: `docker run -it --rm --env-file ./.env ghcr.io/jef/nvidia-snatcher:nightly`

2020-10-06 16:54 UTC, kaysond commented
> I just remove `docker-compose.yml` in order to use directly in cli: `docker run -it --rm --env-file ./.env ghcr.io/jef/nvidia-snatcher:nightly`

That has the same problem, as it requires the env vars to disable sandboxing. You could add something like
`--security-opt seccomp=chrome.json` to the command, if we copied the json from #174.

2020-10-06 18:44 UTC, andrewmackrodt commented on docker/Dockerfile
> +RUN npm run build
The original implementation is a best practice for node.js projects as docker's cache can be utilized for the `npm ci` stage, i.e. if package*.json has not changed, there's no need to download everything from npm again. By having the step after copying src, a single code change means the cache cannot be used.

2020-10-07 00:02 UTC, jef commented on docker/Dockerfile
> +RUN npm run build
Oh yes, that make complete sense. Let's do that.

2020-10-07 00:51 UTC, jef commented
I'm hearing you out @kaysond. I'm going to look at [this](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) and do some debugging. @v1ct0rv, thanks for all the changes. Let's try to get this sucker in.

2020-10-07 01:06 UTC, jef commented
> That has the same problem, as it requires the env vars to disable sandboxing. You could add something like
> `--security-opt seccomp=chrome.json` to the command, if we copied the json from #174.

Okay, so from my testing, I suppose we could either do this, and have a `chrome.json` that we would potentially have to maintain or we can run as `--privileged`. I imagine the side effects are nearly the same, unless a dependency becomes malicious. But I doubt that happening. Especially even if we add in the `chrome.json`, there are a lot of lifted privileges.

I've also added in a user to circumvent some of the access.

2020-10-07 01:28 UTC, jef commented
Alright @v1ct0rv, I'm going to push one commit up, but feel free to revert. Let's discuss and see if everyone is OK with the change.

2020-10-07 01:44 UTC, andrewmackrodt commented
@jef this isn't working for me (Ubuntu host so possible selinux issue):
```
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```
I'd prefer the `BROWSER_TRUSTED` environment variable being able to set `--no-sandbox` is preserved.

2020-10-07 02:18 UTC, jef commented
> A random npm dependency in the image shouldn't be able to change affect my host kernel configuration.

100% agree, that's why I'm also not keen on `chrome.json`.

> you may as well just run the repository on the host directly.

Also my thought. But I guess this is mostly for those who are running the app in some sort of cloud environment that aren't VMs, i.e. k8s (which I don't really think people are doing).

> I'd prefer the BROWSER_TRUSTED environment variable being able to set --no-sandbox is preserved.

Not sure if this helps with at all, but not sure if I understand the sandboxing that Chromium is doing. That being said, it ran on my arch box. Probably an SELinux thing.

Not really sure the best direction to go here. I'd rather not host any Docker image and have someone else manage an image. I don't mind having someone update a wiki page of Docker images, but I'm not too sure if we want to manage this.

2020-10-07 03:23 UTC, kaysond commented
I think it's worth pointing out that all of these are "runtime" options and don't need any changes to the Dockerfile. It's more a question of documentation. I would vote for documenting both choices. Either run with chromiums sandbox and the proper security options, or set the env var and turn off sandboxing. For the chrome.json file you could just include a link to that file from its original source (which I don't remember but can help find - I think it was docker documentation somewhere)

2020-10-07 15:41 UTC, v1ct0rv commented on docker/Dockerfile
> +RUN npm run build
> Alright @v1ct0rv, I'm going to push one commit up, but feel free to revert. Let's discuss and see if everyone is OK with the change.
> 
> https://github.com/jef/nvidia-snatcher/compare/feature/add-docker-support
> 
> Feel free to integrate directly into this PR @v1ct0rv.

Merged.

2020-10-07 16:16 UTC, v1ct0rv commented
> I think it's worth pointing out that all of these are "runtime" options and don't need any changes to the Dockerfile. It's more a question of documentation. I would vote for documenting both choices. Either run with chromiums sandbox and the proper security options, or set the env var and turn off sandboxing. For the chrome.json file you could just include a link to that file from its original source (which I don't remember but can help find - I think it was docker documentation somewhere)

Agreed,  We can run either with `--privileged` or with `--security-opt seccomp=chrome.json` I tested on ubuntu and macos. I suggest to have it both options in the readme.

We can have more granular control with `--security-opt seccomp=chrome.json` but in most cases `--privileged` will be enough.

What do you think?

2020-10-07 22:42 UTC, andrewmackrodt commented
`--privileged` is unnecessary, `--cap-add=SYS_ADMIN` is enough to enable chromium sandboxing.

Regardless, users can do whatever they want regarding their security choices and I would like `--no-sandbox` to remain an option. I'd rather forego the ability to isolate independent tabs from each other than run a container with hundreds of unknown packages from npm with minimal host isolation.

2020-10-08 02:04 UTC, v1ct0rv commented
> `--privileged` is unnecessary, `--cap-add=SYS_ADMIN` is enough to enable chromium sandboxing.
> 
> Regardless, users can do whatever they want regarding their security choices and I would like `--no-sandbox` to remain an option. I'd rather forego the ability to isolate independent tabs from each other than run a container with hundreds of unknown packages from npm with minimal host isolation.

`--cap-add=SYS_ADMIN` grants a smaller subset of capabilities to the container, compared to the `--privileged` switch, I will change then.

Added back the option to Skip Chromium Sandbox.

2020-10-09 20:40 UTC, jef reviewed
> Regardless, users can do whatever they want regarding their security choices and I would like `--no-sandbox` to remain an option

Do we have to enable sandboxing to run the `Dockerfile`? If so, maybe we should add `config.docker` to

```
	if (config.browser.isTrusted || config.docker) {
		args.push('--no-sandbox');
		args.push('--disable-setuid-sandbox');
	}
```

Haven't ran yet though, so just an assumption...

2020-10-09 20:55 UTC, andrewmackrodt commented
> Do we have to enable sandboxing to run the Dockerfile?

It's dependent on what privileges the user has allowed. If they're running with an appropriate security profile or using `--cap-add=SYS_ADMIN` then sandboxing will be supported. It's only cases where neither are set as a runtime argument that we would want to apply `--no-sandbox`.

2020-10-09 20:57 UTC, kaysond commented
> Do we have to enable sandboxing to run the `Dockerfile`?
I think its a question of what you want the "default" to be, but its completely arbitrary since users can change it when they run the container.

By default right now (I think), sandboxing is enabled, which requires users to either user the Docker option `--cap-add=SYS_ADMIN` or --security-opt seccomp=chrome.json`. This is totally normal practice and there are plenty of containers that require additional permissions.

If a user wants to disable the sandbox, then they run with `--env-file <file>` or `--env BROWSER_TRUSTED=TRUE`

I would strongly recommend not having different defaults if you're running natively or in a container, i.e. run with sandboxing enabled unless specified by the env var, both in native and container environments.

2020-10-09 21:41 UTC, jef commented
Thank you two for that explanation. And thank you @v1ct0rv for seeing this through. Appreciate everyone's help and discussion.

Alright, well, let's see how this thing goes...

2020-10-09 21:42 UTC, jef approved these changes

2020-10-09 21:42 UTC, merged

2020-10-09 22:03 UTC, jef commented
Annnndd... Actions are down right 😢 

![image](https://user-images.githubusercontent.com/12074633/95635209-c5b0d680-0a59-11eb-9fbb-f0df50d437a1.png)