feat: add incognito mode
jef/nvidia-snatcher pull request #534
Opened 2020-10-17 18:43 UTC by GRINSPANKER13

### Description
Added the ability to use Incognito tabs.
At least with chrome, it uses a cache for sites, incognito forces to reload everything.
This might help better detect when the "add to cart" button is updated.

### Testing
Tested with a normal link with "headless:false" to see if it actually opens in "incognito" and it does.

![001](https://user-images.githubusercontent.com/20674650/96351042-36697b80-1076-11eb-9c2e-a2b9ea172364.png)

![002](https://user-images.githubusercontent.com/20674650/96351045-3cf7f300-1076-11eb-97ee-71b7ffbf4397.png)

### New dependencies

2020-10-19 15:17 UTC, jef requested changes
Looks good overall! Just the one comment. Let me know what you think.

Thanks!

2020-10-19 15:17 UTC, jef commented on src/store/lookup.ts
> +		const page = (config.browser.isIncognito ? await context.newPage() : await browser.newPage());
I'd wrap this context within the if statement as well, so we don't create the incognito browser context without needing to.

2020-10-19 23:16 UTC, GRINSPANKER13 commented
> Looks good overall! Just the one comment. Let me know what you think.
> 
> Thanks!

I'm not sure how you would wrap it in an if statement, but every browser has a BrowserContext by default, so I changed the code to assign context to be either default or incognito. Also, closing the page, closed the default BrowserContext, but you have to close the incognito BrowserContext separately. What do you think?

2020-10-20 04:16 UTC, jef commented
Ah, that makes a lot of sense to me now. I remember being a little confused when I was playing with the context and passing it around in a feature branch I was working in.

Thanks for the explanation!

2020-10-20 04:17 UTC, jef approved these changes

2020-10-20 16:07 UTC, merged